config/routes.rb
SecurityApp::Application.routes.draw do
  namespace :admin do
    resources :users
  end

  resource :session

  resources :users

  namespace :admin do
    resources :cats do
      collection do
        get :image
      end
    end
    resources :comments
  end

  resources :comments

  resources :cats do
    collection do
      get :image
    end
  end

  root to: "cats#index"

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_protected

  validates_presence_of :comment, :cat

  belongs_to :user
end

app/models/session.rb
class Session < Struct.new(:username, :password)
  def self.model_name; ActiveModel::Name.new(Session); end

  def user
    user = User.where(username: username).first
    user if user && user.password == password
  end

  def to_key
    ["session"]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_protected
  validates_presence_of :username, :password
  validates_uniqueness_of :username

  has_many :comments
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ::ApplicationController

  before_filter :validate_role

  def validate_role
    redirect_to root_path unless current_user && current_user.role == "admin"
  end

end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < Admin::ApplicationController
  
  def index
    @cats = `ls #{Rails.root}/cats`.chomp.split
  end

  def show
    @cat = URI.unescape params[:id]
    
    @comments = ::Comment.where("cat = '#{@cat}'")
  end

  def image
    @cat = params[:cat]
    filename = Rails.root.join "cats", @cat
    send_file filename, disposition: "inline"
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  
  def destroy
    comment = ::Comment.find(params[:id])
    cat = comment.cat
    comment.destroy
    flash[:notice] = "Comment deleted."
    redirect_to admin_cat_path(cat.sub(".", "%252e"))
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  def index
    filter = params[:filter] || "1=1"
    @users = User.where(filter)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "User deleted."
    redirect_to admin_users_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  def current_user
    @current_user ||= User.where(id: session[:user_id]).first
  end

  helper_method :current_user
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Dir.glob(Rails.root.join("cats", "*")).map(&File.method(:basename))
  end

  def show
    @cat = URI.unescape params[:id]
    
    @comment = Comment.new cat: @cat

    @comments = Comment.where("cat = '#{@cat}'")
  end

  def image
    @cat = params[:cat]
    filename = cat_dir.join @cat
    if filename.dirname == cat_dir # only allow cats to be downloaded!
      send_file filename, disposition: "inline"
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  private

  def cat_dir
    Rails.root.join("cats")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new params[:comment]
    if @comment.save
      flash[:notice] = "Posted your comment!"
      redirect_to cat_path(@comment.cat.sub(".", "%252e"))
    else
      flash.now[:error] = @comment.errors.full_messages.to_sentence
      @cat = @comment.cat
      render "cats/show"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(params[:session][:username], params[:session][:password])
    if @session.user
      session[:user_id] = @session.user.id
      redirect_to :root
    else
      flash.now[:error] = "Unknown username or password, please try again"
      render :new
    end
  end

  def edit
    session.delete :user_id
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      session[:user_id] = @user.id
      redirect_to cats_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end
end

app/helpers/admin/cats_helper.rb
module Admin::CatsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def exif cat
    filename = Rails.root.join "cats", cat
    `identify #{filename}`.chomp
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/cats/.#show.html.erb
bodhi@pasokun.local.1445

app/views/admin/cats/index.html.erb
<h1>Admin: Cats</h1>

<table>
  <thead>
  <tr>
    <th>Filename</th>
    <th>Comments</th>
    <th>Image</th>
  </tr>
  </thead>
    <tbody>
      <% @cats.each do |cat| %>
        <tr>
          <td class="filename"><%= link_to cat, admin_cat_path(cat.sub(".", "%252e")) %><br><%= exif cat %></td>
          <td class="comment-count"><%= Comment.where(cat: cat).count %></td>
          <td class="image"><%= image_tag image_cats_path(cat: cat) %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/admin/cats/show.html.erb
<div id="cat">
  <%= image_tag(image_admin_cats_path(cat: @cat)) %>
</div>
<div id="meta">
  <% exif = exif(@cat).split %>
  <%= exif[2] %>
  <%= exif[1] %>
  <%= exif[6] %>
</div>

<div id="comments">
  <h2>Comments</h2>

  <table>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.username %> </td>
        <td><%= comment.created_at %></td>
        <td>
          <%== comment.comment %>
        </td>
        <td>
        <%= button_to "Delete", admin_comment_path(comment), method: :delete, confirm: "Really delete this comment?" %>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/users/index.html.erb
<h1>Admin: Users</h1>

<%= link_to "All", admin_users_path %> :: 
<%= link_to "Users", admin_users_path(filter: "role='user'") %> ::
<%= link_to "Admins", admin_users_path(filter: "role='admin'") %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Role</th>
    <th></th>
  </tr>
  </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.password %></td>
          <td><%= user.role %></td>
          <td>
            <%= button_to "Delete", admin_user_path(user), method: :delete, confirm: "Really delete this user?" %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/cats/_cat.html.erb
<div class="cat span2">
  <%= link_to image_tag(image_cats_path(cat: cat)), cat_path(cat.sub(".", "%252e")) %>
</div>

app/views/cats/_comment.html.erb
<li>
  <div><strong><%= comment.user.username %></strong> <%= time_ago_in_words comment.created_at %> ago</div>
  <div>
    <%== comment.comment %>
  </div>
</li>

app/views/cats/index.html.erb
<h1>Cats</h1>

<div id="cat-list">
  <%= render partial: "cat", collection: @cats %>
</div>

app/views/cats/show.html.erb
<div id="cat">
<%= image_tag(image_cats_path(cat: @cat)) %>
</div>
<div id="meta">
  <% exif = exif(@cat).split %>
  <%= exif[2] %>
  <%= exif[1] %>
  <%= exif[6] %>
</div>

<div id="comments">
<h2>Comments</h2>

<% if current_user %>
  <%= form_for @comment do |f| %>
  <%= f.text_area :comment %>
  <%= f.hidden_field :cat %>

  <div>
    <%= f.button "Say It!!!", class: "btn btn-primary" %>
  </div>
<% end %>
<% end %>

<ol>
  <%= render partial: "comment", collection: @comments %>
</ol>
</div>

app/views/users/new.html.erb
<h1>Register for Cats!</h1>

<p>Register to comment and bookmark cats</p>

<%= form_for @user do |f| %>
  
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <div>
    <%= f.button "Let Me Comment On The Cats!!!", class: "btn btn-primary" %>
  </div>
<% end %>