config/routes.rb
SecurityApp::Application.routes.draw do
  namespace :admin do
    resources :users
  end

  resource :session

  resources :users

  namespace :admin do
    resources :cats do
      collection do
        get :image
      end
    end
    resources :comments
  end

  resources :comments

  resources :cats do
    collection do
      get :image
    end
  end

  root to: "cats#index"

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_protected

  validates_presence_of :comment, :cat

  belongs_to :user
end

app/models/session.rb
class Session < Struct.new(:username, :password)
  def self.model_name; ActiveModel::Name.new(Session); end

  def user
    user = User.where(username: username).first
    user if user && user.password == password
  end

  def to_key
    ["session"]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_protected
  validates_presence_of :username, :password
  validates_uniqueness_of :username

  has_many :comments
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < Admin::ApplicationController
  
  def index
    @cats = `ls #{Rails.root}/cats`.chomp.split
  end

  def show
    @cat = URI.unescape params[:id]
    
    @comments = ::Comment.where("cat = '#{@cat}'")
  end

  def image
    @cat = params[:cat]
    filename = Rails.root.join "cats", @cat
    send_file filename, disposition: "inline"
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  
  def destroy
    comment = ::Comment.find(params[:id])
    cat = comment.cat
    comment.destroy
    flash[:notice] = "Comment deleted."
    redirect_to admin_cat_path(cat.sub(".", "%252e"))
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  def index
    filter = params[:filter] || "1=1"
    @users = User.where(filter)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "User deleted."
    redirect_to admin_users_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  def current_user
    @current_user ||= User.where(id: session[:user_id]).first
  end

  helper_method :current_user
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Dir.glob(Rails.root.join("cats", "*")).map(&File.method(:basename))
  end

  def show
    @cat = URI.unescape params[:id]
    
    @comment = Comment.new cat: @cat

    @comments = Comment.where("cat = '#{@cat}'")
  end

  def image
    @cat = params[:cat]
    filename = cat_dir.join @cat
    if filename.dirname == cat_dir # only allow cats to be downloaded!
      send_file filename, disposition: "inline"
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  private

  def cat_dir
    Rails.root.join("cats")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.new params[:comment]
    if @comment.save
      flash[:notice] = "Posted your comment!"
      redirect_to cat_path(@comment.cat.sub(".", "%252e"))
    else
      flash.now[:error] = @comment.errors.full_messages.to_sentence
      @cat = @comment.cat
      render "cats/show"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(params[:session][:username], params[:session][:password])
    if @session.user
      session[:user_id] = @session.user.id
      redirect_to :root
    else
      flash.now[:error] = "Unknown username or password, please try again"
      render :new
    end
  end

  def edit
    session.delete :user_id
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      session[:user_id] = @user.id
      redirect_to cats_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end
end

app/helpers/admin/cats_helper.rb
module Admin::CatsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def exif cat
    filename = Rails.root.join "cats", cat
    `identify #{filename}`.chomp
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cats" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <nav class="navbar navbar-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Cats!</a>
          <div class="container nav-collapse">
            <% if current_user %>
              <ul class="nav">
                <li><%= link_to "Logged in as #{current_user.username}", root_path %></li>
                <li><%= link_to "Log Out", edit_session_path  %></li>

                <% if current_user.role != "user" %>
                <li><%= link_to "Admin Cats", admin_cats_path  %></li>
                <li><%= link_to "Admin Users", admin_users_path  %></li>

                <% end %>
              </ul>
              <% else %>
              <ul class="nav">
                <li><%= link_to "Log In", new_session_path  %></li>
                <li><%= link_to "Register", new_user_path  %></li>
              </ul>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </nav>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Swiss Cheese Co.</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>